=== coeing/cframework/framework/data/common/ctrls/styles/gui_style.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.oeing.eu/cframework/schemas/ctrls/styles"
  targetNamespace="http://www.oeing.eu/cframework/schemas/ctrls/styles"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation xml:lang="DE">
      CGui GUI Style Schema.
      Copyright 2008 Christian Oeing. Alle Rechte vorbehalten.
    </xs:documentation>
  </xs:annotation>
  <xs:include schemaLocation="./button_style.xsd"/>
  <xs:complexType name="GuiStyleElementType">
    <xs:attribute name="xml_file" type="xs:string"  use="required" />
    <xs:attribute name="name"     type="xs:string"  use="required" />
    <xs:attribute name="default"  type="xs:boolean" default="false" />
  </xs:complexType>
  <xs:complexType name="GuiStyleType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="ctrl_style" type="GuiStyleElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:element name="gui_style" type="GuiStyleType"/>
</xs:schema>

=== coeing/cframework/framework/data/common/ctrls/styles/default/default_gui_style.xml
<?xml version="1.0" encoding="utf-8"?>
<gui_style xmlns="http://www.oeing.eu/cframework/schemas/ctrls/styles"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.oeing.eu/cframework/schemas/ctrls/styles ../gui_style.xsd">
   <ctrl_style type="button"    xml_file="default_button_style.xml"         name="DefaultButton"        default="true"/>
   <ctrl_style type="editbox"   xml_file="default_editbox_style.xml"        name="DefaultEditBox"       default="true"/>
   <ctrl_style type="listbox"   xml_file="default_listbox_style.xml"        name="DefaultListBox"       default="true"/>
   <ctrl_style type="column"    xml_file="default_listboxcolumn_style.xml"  name="DefaultListBoxColumn" default="true"/>
   <ctrl_style type="checkbox"  xml_file="default_checkbox_style.xml"       name="DefaultCheckBox"      default="true"/>
   <ctrl_style type="combobox"  xml_file="default_combobox_style.xml"       name="DefaultComboBox"      default="true"/>
   <ctrl_style type="textbox"   xml_file="default_textbox_style.xml"        name="DefaultTextBox"       default="true"/>
  <ctrl_style type="tree"       xml_file="default_tree_style.xml"           name="DefaultTree"          default="true"/>
</gui_style>

=== coeing/cframework/framework/samples/cmadtv/build/data/ctrls/styles/gui_style.xml
<?xml version="1.0" encoding="utf-8"?>
<gui_style xmlns="http://www.oeing.eu/cframework/schemas/ctrls/styles"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.oeing.eu/cframework/schemas/ctrls/styles ../../../common/ctrls/styles/gui_style.xsd">
  <ctrl_style name="ButtonBackground" xml_file="button_background.xml"/>
  <ctrl_style name="StdButton" default="true" xml_file="std_button.xml"/>
  <ctrl_style name="BigButtonRed" xml_file="big_button_red.xml"/>
  <ctrl_style name="BigButtonBlue" xml_file="big_button_blue.xml"/>
  <ctrl_style name="StdEditBox" xml_file="std_editbox.xml"/>
  <ctrl_style name="EditBoxLoadSave" xml_file="editbox_load_save.xml"/>
  <ctrl_style name="SquareButtonBackground" xml_file="square_button_background.xml"/>
  <ctrl_style name="ArrowButton" xml_file="arrow_button.xml"/>
  <ctrl_style name="StdComboBox" xml_file="std_combobox.xml" />
  <ctrl_style name="StdProgressBar" xml_file="std_progressbar.xml"/>
  <ctrl_style name="StdListBox" xml_file="std_listbox.xml" />
  <ctrl_style name="StdScrollBar" xml_file="std_scrollbar.xml" />
  <ctrl_style name="StdScrollPanel" xml_file="std_scrollpanel.xml" />
</gui_style>
