=== coeing/cframework/framework/data/common/ctrls/panel.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://cframework.oeing.eu/schemas/ctrls"
           targetNamespace="http://cframework.oeing.eu/schemas/ctrls"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation xml:lang="DE">
			CGui Panel Schema.
			Copyright 2006 Christian Oeing. Alle Rechte vorbehalten.
		</xs:documentation>
  </xs:annotation>
  <xs:include schemaLocation="./button.xsd"/>
  <xs:include schemaLocation="./mesh.xsd"/>
  <xs:include schemaLocation="./checkbox.xsd"/>
  <xs:include schemaLocation="./editbox.xsd"/>
  <xs:include schemaLocation="./listbox.xsd"/>
  <xs:include schemaLocation="./combobox.xsd"/>
  <xs:include schemaLocation="./scrollbar.xsd"/>
  <xs:include schemaLocation="./scrollpanel.xsd"/>
  <xs:include schemaLocation="./window.xsd"/>
  <xs:include schemaLocation="./scaleimage.xsd"/>
  <xs:complexType name="PanelType">
    <xs:complexContent>
      <xs:extension base="ObjectType">
        <xs:sequence>
          <xs:element name="state_normal"           type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:element name="state_highlight"        type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:element name="state_active"           type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:element name="state_active_highlight" type="StateType" minOccurs="0" maxOccurs="1"/>
          <xs:element name="state_disabled"         type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:element name="state_modified"         type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:element name="state_information"      type="StateType" minOccurs="0" maxOccurs="1" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="object"		    type="ObjectType" />
            <xs:element name="panel"		    type="PanelType" />
            <xs:element name="window"		    type="WindowType" />
            <xs:element name="button"		    type="ButtonType" />
            <xs:element name="image"		    type="ImageType" />
            <xs:element name="mesh"		      type="MeshType" />
            <xs:element name="textbox"		  type="TextBoxType" />
            <xs:element name="checkbox"     type="CheckBoxType"/>
            <xs:element name="editbox"      type="EditBoxType" />
            <xs:element name="listbox"      type="ListBoxType" />
            <xs:element name="combobox"     type="ComboBoxType"/>
            <xs:element name="scaleimage"   type="ScaleImageType" />
            <xs:element name="scrollbar"    type="ScrollBarType"/>
            <xs:element name="scrollpanel"  type="ScrollPanelType"/>
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== coeing/cframework/framework/samples/cmadtv/build/data/windows/StatsRatingBar.xml
<?xml version="1.0" encoding="utf-8"?>
<panel xmlns="http://cframework.oeing.eu/schemas/ctrls"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://cframework.oeing.eu/schemas/ctrls ../../common/ctrls/panel.xsd"
   name="StatsImageBar" size_mode="content" bg_visible="false">
  <image name="ImgShadowNews" offset_x="12" offset_y="158" local_attach_point="bottom left" width="28" height="150" bg_color="000000" />
  <panel name="PnlBarNews" offset_x="4" offset_y="150" local_attach_point="bottom left" width="28" height="150" bg_visible="false">
    <image name="ImgBorder" size_mode="stretch" bg_color="000000"/>
    <image name="ImgColor" offset_x="2" offset_y="2" size_mode_y="stretch" width="24" bg_color="ffffff"/>
  </panel>
  <image name="ImgShadow" offset_x="24" offset_y="158" local_attach_point="bottom left" width="40" height="150" bg_color="000000" />
  <panel name="PnlBar" offset_x="16" offset_y="150" local_attach_point="bottom left" width="40" height="150" bg_visible="false">
    <image name="ImgBorder" size_mode="stretch" bg_color="000000"/>
    <image name="ImgColor" offset_x="2" offset_y="2" size_mode_y="stretch" width="36" bg_color="ffffff"/>
  </panel>
  <textbox name="TbHour" offset_x="0" offset_y="156" width="56" height="22" bg_visible="false" text_align_horizontal="center" text="18"/>
  <image name="ImgArrowUp" offset_x="27" offset_y="172" local_attach_point="top" size_mode="content" bg_visible="false" angle="180">
    <state_normal texture="data/art/windows/StatsRatingsWindow/arrow.png" />
  </image>
  <image name="ImgArrowDown" offset_x="27" offset_y="172" local_attach_point="top" size_mode="content" bg_visible="false">
    <state_normal texture="data/art/windows/StatsRatingsWindow/arrow.png" />
  </image>
</panel>

=== coeing/cframework/framework/samples/cmadtv/build/data/windows/SpectatorsTooltip.xml
<?xml version="1.0" encoding="utf-8"?>
<panel xmlns="http://www.oeing.eu/cframework/schemas/ctrls"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.oeing.eu/cframework/schemas/ctrls ../../common/ctrls/panel.xsd"
   name="SpectatorsTooltip" width="238" height="108" bg_visible="false">
  <image name="ImgBackground" size_mode="stretch" texture="data/art/windows/InfoWindow/spectators_tooltip_bg.png" bg_visible="false" />
  <textbox name="TbMaxViewersTitle" offset_x="2" offset_y="4" size_mode="custom" width="230" height="16" text="Maximum viewers:" padding_left="18" font_size="12" bg_visible="false" />
  <textbox name="TbMaxViewers" offset_x="2" offset_y="20" size_mode="custom" width="230" height="16" text="N/A" padding_left="18" font_size="12" bg_color="0xb0b0b0" />
  <textbox name="TbRatingTitle" offset_x="2" offset_y="36" size_mode="custom" width="230" height="16" text="Current rating:" padding_left="18" font_size="12" bg_visible="false" />
  <textbox name="TbRating" offset_x="2" offset_y="52" size_mode="custom" width="230" height="16" text="N/A" padding_left="18" font_size="12" bg_color="0xb0b0b0" />
  <textbox name="TbNextAdvertTitle" offset_x="2" offset_y="68" size_mode="custom" width="230" height="16" text="Next advert:" padding_left="18" font_size="12" bg_visible="false" />
  <textbox name="TbNextAdvert" offset_x="2" offset_y="84" size_mode="custom" width="230" height="16" text="N/A" padding_left="18" font_size="12">
    <state_normal bg_color="0xb0b0b0" />
    <state_active bg_color="0xdc2424" />
  </textbox>
</panel>
